import toast from "react-hot-toast";
import { Button } from "./components/ui/button";

function App() {
  return (
    <div className="flex justify-center pt-[200px]">
      <div className="flex flex-col gap-[20px]">
        <h4
          className="scroll-m-20 text-start 
      text-3xl font-bold tracking-tight text-balance pb-[20px]"
        >
          Project generated by n73
        </h4>
        <Button
          onClick={() => {
            toast.success("Hello from toast!");
          }}
          variant="secondary"
        >
          Click me!
        </Button>
      </div>
    </div>
  );
}

export default App;
